### ISSUE TITLE
Password should be of type Secret

### ISSUE THREAD

**Issue by Jaxwood** [puzzle/dagger-module-helm#21]
Hi,

Thanks for your module.

Currently password is handled as a string - dagger exposes a type `dagger.Secret`.

Using `dagger.Secret` would hide the password in logs.

Would it be possible to change it to type `dagger.Secret`?

**Comment by chrira** [comment]
Hello.
Thanks for your proposal!
I'll change it to a Dagger Secret.

**Comment by chrira** [comment]
@Jaxwood The new version v1.0.0 of the module now uses a secret for the password.
I also changed to the stdin method for `helm registry login`.

Moudle: https://daggerverse.dev/mod/github.com/puzzle/dagger-module-helm/helm@03b5661b7c1c49318f9546a93d349bccdb88894d
